service: ${file(config.json):SERVICE_NAME}

plugins:
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource: ${file(config.json):FROM_ARN}

functions:
  encrypt:
    handler: src/handlers/encrypt/handler.handle
    events:
      - http:
          path: /encrypt/{_email}
          method: any
          request:
            parameters:
              querystrings:
                _format: true
              paths:
                _email: true
  receive:
    handler: src/handlers/receive/handler.handle
    events:
      - http:
          path: /to/{_to}
          method: post
          request:
            parameters:
              querystrings:
                _format: true
              paths:
                _to: true
  send:
    handler: src/handlers/send/handler.handle 
